[30;1m2023-02-16 11:05:16[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-02-16 11:05:17[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 95f24914e4363d905c5a0170b6913c77).
[30;1m2023-02-16 11:10:06[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-02-16 11:10:07[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 2a4f6402b288e6130ea72c7e563a6bd5).
[30;1m2023-02-16 13:46:02[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 14:25:43[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 15:09:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 15:40:53[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 16:20:36[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 17:02:09[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 17:35:15[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 18:00:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 21:45:56[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-16 22:12:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 00:39:40[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 02:56:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 04:57:21[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 05:14:12[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 05:34:41[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 07:38:20[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 08:10:09[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 08:42:15[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 09:53:15[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 10:36:35[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 12:14:53[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 13:18:48[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 16:31:57[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-17 17:05:21[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 2a4f6402b288e6130ea72c7e563a6bd5.
[30;1m2023-02-23 10:57:59[0m [34;1mINFO    [0m [35mdiscord.client[0m logging in using static token
[30;1m2023-02-23 10:58:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: 6809657b993e49b868567e520edacd16).
[30;1m2023-02-23 11:39:45[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 13:11:44[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 16:46:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 17:24:16[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 18:42:44[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 19:19:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 19:42:02[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 21:43:24[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-23 22:57:20[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session 6809657b993e49b868567e520edacd16.
[30;1m2023-02-24 00:10:09[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 0.39s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:11:10[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 3.01s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:12:13[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 5.73s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:13:18[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 9.81s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:14:28[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 11.24s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:15:40[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 17.59s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:16:57[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 117.63s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:19:55[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 241.06s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:24:56[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 213.21s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:29:29[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 867.73s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:44:57[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 144.62s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:48:22[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 84.04s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 00:50:46[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 674.34s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:03:01[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 15.68s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:04:16[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 185.49s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:08:22[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 323.89s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:14:46[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 67.56s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:16:54[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 940.50s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:33:34[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 261.01s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:38:55[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 14.49s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:40:10[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 713.67s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 01:53:04[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 549.73s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 02:03:13[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 691.48s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 02:15:45[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 813.04s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 02:30:18[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 39.92s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 02:31:58[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 657.51s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 02:43:56[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 611.28s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 02:55:07[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 278.86s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 03:00:46[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 887.75s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 03:16:34[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 459.11s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 03:25:13[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 13.87s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 03:26:27[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 977.41s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 03:43:44[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 851.97s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 03:58:57[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 867.79s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 04:14:24[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 440.62s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 04:22:45[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 331.49s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 04:29:17[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 809.64s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 04:43:46[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 879.87s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 04:59:26[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 591.36s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:10:18[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 31.67s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:11:49[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 342.60s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:18:32[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 136.06s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:21:48[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 940.15s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:38:29[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 278.44s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:44:07[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 845.49s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 05:59:13[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 891.86s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 06:15:05[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 952.97s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 06:31:58[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 338.42s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 06:38:36[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 700.66s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 06:51:17[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 162.47s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 06:54:59[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 175.44s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 06:58:55[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 423.45s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 07:06:58[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 43.80s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 07:08:42[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 782.63s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 07:22:45[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 958.70s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 07:39:44[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 477.74s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 07:48:42[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 550.35s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 07:58:52[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 255.51s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 08:04:08[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 417.90s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 08:12:06[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 651.99s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 08:23:58[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 332.27s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 08:30:30[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 1013.57s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 08:48:24[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 968.72s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 09:05:33[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 385.38s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 09:12:58[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 970.78s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 09:30:09[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 319.10s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 09:36:28[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 26.22s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 09:37:55[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 989.18s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 09:55:24[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 710.18s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 10:08:14[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 337.30s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 10:14:52[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 475.34s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 10:23:47[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 827.13s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 10:38:34[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 502.53s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 10:47:57[0m [31mERROR   [0m [35mdiscord.client[0m Attempting a reconnect in 647.15s
[31mTraceback (most recent call last):
  File "/home/nlpuser/.local/lib/python3.8/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError[0m
[30;1m2023-02-24 10:58:44[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None session has been invalidated.
[30;1m2023-02-24 10:58:50[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has connected to Gateway (Session ID: cafd4f6271dfaa5446bc44db683e4b2b).
[30;1m2023-02-24 11:30:32[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-24 13:28:16[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-24 14:48:54[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-24 16:10:25[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-24 20:01:31[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-24 22:53:07[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 01:13:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 03:24:22[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 05:31:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 09:09:14[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 09:56:48[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 10:17:32[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 13:49:28[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 16:58:28[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 19:37:17[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 20:08:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 22:28:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-25 23:26:19[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 00:19:41[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 02:46:14[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 05:40:54[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 06:16:45[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 09:24:50[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 11:49:42[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 13:55:07[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 16:12:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 17:08:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 18:07:10[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 18:28:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 21:42:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-26 22:19:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 01:28:28[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 02:46:16[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 04:53:07[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 07:04:26[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 09:22:29[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 11:25:22[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 12:11:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 12:26:39[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 13:58:40[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 15:09:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 17:56:02[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 18:41:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 21:10:25[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-27 23:06:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 01:33:29[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 02:18:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 03:35:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 05:27:06[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 09:19:58[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 10:42:57[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 11:48:22[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 13:38:10[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 16:29:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 18:02:13[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 21:51:45[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-02-28 23:36:35[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 02:44:31[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 03:56:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 04:27:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 06:54:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 09:00:15[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 12:56:48[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 15:08:46[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 15:52:09[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 18:58:29[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 20:38:27[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-01 23:28:58[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 01:47:22[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 03:12:07[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 06:24:03[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 07:10:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 09:08:21[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 09:35:23[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 10:22:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 11:29:36[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 13:38:25[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 14:07:27[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 15:58:07[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 17:29:41[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 18:34:29[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 22:21:55[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-02 22:53:29[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 00:12:30[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 00:18:18[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 01:28:35[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 03:14:53[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 07:07:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 07:37:44[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 09:22:56[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 11:39:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 14:19:37[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 16:13:36[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 19:49:31[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-03 21:52:58[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 00:15:16[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 03:48:08[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 05:24:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 05:50:35[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 09:33:20[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 13:00:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 14:02:24[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 14:31:38[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 15:49:34[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 18:48:48[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 19:23:05[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 20:46:15[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-04 23:21:31[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 03:15:44[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 04:38:04[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 07:42:27[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 11:38:10[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 13:19:24[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 16:00:47[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 16:23:00[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
[30;1m2023-03-05 17:17:10[0m [34;1mINFO    [0m [35mdiscord.gateway[0m Shard ID None has successfully RESUMED session cafd4f6271dfaa5446bc44db683e4b2b.
